ALTER TABLE STUDENT  ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE MARK ADD CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE MARK ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE MARK ALTER COLUMN subject_id BIGINT NOT NULL;

