ALTER TABLE STUDENT  ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE MARK ADD CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE MARK ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE MARK ALTER COLUMN subject_id BIGINT NOT NULL;

ALTER TABLE SUBJECT ADD CHECK(grade >= 1 AND grade <=5);

ALTER TABLE PAYMENTTYPE ADD UNIQUE (name);

ALTER TABLE PAYMENT ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN amount DECIMAL NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN payment_date DATETIME NOT NULL;


